rails/config/routes.rb
Rails.application.routes.draw do
  get    '/service_worker', to: 'service_worker#service_worker'
  resources :push_subscriptions, only: :create
  resources :groups
  resources :users
  resources :messages
  get    '/messages/group/:id/new', to: 'messages#group_new', as: :new_group_message
  get    '/names_search/:query', to: 'names_search#search'
  get    '/groups/:id/user/:user_id', to: 'groups#add_remove_user', as: :user_in_group
  get    '/users/:id/accept', to: 'users#accept', as: :accept_user
  get    '/register' => 'register#new'
  post   '/register' => 'register#create'
  get    '/confirm/:id'  => 'register#confirm'
  get    '/password/:id'  => 'password#edit'
  post   '/password'  => 'password#update'
  get    '/login'    => 'sessions#new'
  post   '/login'    => 'sessions#create'
  delete '/logout'   => 'sessions#destroy'
  get    '/administration' => 'sessions#administration'
  get    '/impressum' => 'impressum#index'
  get    '/datenschutz' => 'impressum#datenschutz'
  get    '/logs'  => 'logs#index'
  root   'home#index'
end
  

rails/app/models/user.rb
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/

class User < ApplicationRecord
  before_save { 
    self.email = email.downcase
  }
  
  validates :name, presence: true, length: { maximum: 50 }

  validates :email, presence: true, length: { maximum: 255 },
     format: { with: VALID_EMAIL_REGEX },
     uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, if: :password_validation

  has_and_belongs_to_many :groups
  has_many :messages, dependent: :destroy
  has_many :push_subscriptions, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy, class_name: "Noticed::Notification"

  def self.find_by_confirmation(id)
    user = self.find_by confirm_hash: id
    if user && user.confirm_at < DateTime.now
      user.reset_confirmation
      user = nil
    end
    user
  end

  def reset_confirmation
    self.confirm_hash = nil
    self.confirm_at = nil
    self.save
  end

  def password_validation
    new_record? || password_digest_changed?
  end

  def admin?
    self.user && self.admin
  end

  def user?
    self.user
  end

  # registered but not yet confirmed
  def registered?
    !self.user && !self.confirmed && self.confirm_hash 
  end

  # registered and confirmed (waiting for admin's approval)
  def candidate?
    !self.user && self.confirmed 
  end

  def display_role
    if self.admin?
      return 'Moderator'
    elsif self.user?
      return 'Benutzer'
    elsif self.candidate?
      return 'Kandidat'
    else
      return 'Bewerber'
    end
  end

  def clear_messages
    false
  end

end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Benutzer '#{@user.name}' wurde zugefügt"
      log "Neuer Benutzer '#{@user.name}', id: #{@user.id}"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    u_params = administration? ? admin_params : user_params
    if administration?
      if u_params[:group_ids]
        u_params[:group_ids] = u_params[:group_ids].map {|id| id.to_i}.delete_if {|id| id <= 0}
      end
      if u_params[:clear_messages]
        u_params.extract! :clear_messages
        u_params[:messages] = []
      end
    end
    if @user.update(u_params)
      flash.now[:success] = "Benutzer wurde aktualisiert"
      log "Benutzer '#{@user.name}' wurde aktualisiert"
      redirect_to users_url
    else
      flash.now[:danger] = "Kann Benutzer nicht aktualisieren"
      render_toast
    end
  end

  def destroy
    user = User.find(params[:id])
    if administration? && user && current_user.id != user.id && user.name != 'admin'
      if user.destroy
        flash[:success] = "Benutzer '#{user.name}' wurde gelöscht"
        log "Benutzer gelöscht '#{user.name}', id: #{user.id}"
        redirect_to users_url
        return
      end
    end
    flash.now[:danger] = "Kann Benutzer '#{user ? user.name : '?'}' nicht löschen"
    render_toast
  end

  def accept
    user = User.find(params[:id])
    if current_user.admin? && user && user.candidate?
      user.user = true
      if user.save
        GroupMailer.user_welcome(user, request_url).deliver
        flash[:success] = "Kandidat wurde akzeptiert"
        log "Kandidat wurde akzeptiert '#{user.name}'"
        redirect_to users_url
      else
        flash.now[:danger] = "Kandidat wurde nicht akzeptiert!"
        render_toast
      end
    else
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def admin_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
                      :admin, :confirmed, :user, :clear_messages, :group_ids => [])
  end

end

rails/app/helpers/users_helper.rb
module UsersHelper
end

rails/app/views/users/edit.html.erb
<div class="usk-header">Benutzer: <%= @user.name %></div>

<%= form_for(@user) do |f| %>

  <div>
    <%= f.label :name, 'Name:', class: "form-label" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Benutzername" %>
  </div>

  <div>
    <%= f.label :email, 'E-Mail:', class: "form-label" %>
    <%= f.text_field :email, class: "form-control", placeholder: "E-Mail" %>
  </div>

  <div class="form-check">
    <%= f.check_box :confirmed, class: "form-check-input" %>
    <%= f.label :confirmed, 'E-Mail bestätigt', class: "form-check-label" %>
  </div>

  <div class="form-check">
    <%= f.check_box :user, class: "form-check-input" %>
    <%= f.label :user, 'ist User', class: "form-check-label" %>
  </div>

  <div class="form-check">
    <%= f.check_box :admin, class: "form-check-input" %>
    <%= f.label :admin, 'ist Administrator', class: "form-check-label" %>
  </div>

  <div class="form-check">
    <%= f.check_box :clear_messages, class: "form-check-input" %>
    <%= f.label :clear_messages, 'alle Mitteilungen löschen (' + @user.message_ids.size.to_s + ')', class: "form-check-label" %>
  </div>

  <table class="table table-striped table-hover">

    <thead>
      <tr class="table-primary">
        <th>Gruppe</th>
        <th>ist Mitglied</th>
      </tr>
    </thead>

    <tbody>
      <%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) do |b| %>
        <tr>
          <td><%= b.label %></td>
          <td>
            <%= b.check_box class: "form-check-input" %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>

  <div class="usk-btn-group">
    <%= f.submit "Speichern", class: "btn btn-primary" %>
    <%= link_to "Abbrechen", users_path, class: "btn btn-danger" %>
  </div>

<% end %>

rails/app/views/users/index.html.erb
<div class="d-flex justify-content-between">
  <div class="usk-header">Benutzer:</div>
  <% if administration? %>
    <%= link_to new_user_path do %>
      <%= render 'layouts/add_button', tooltip: 'Neuer Benutzer' %>
    <% end %>
  <% end %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr class="table-primary">
      <th></th>
      <th>Name</th>
      <th>E-Mail</th>
      <th>Role</th>
      <% if administration? %>
        <th>Aktion</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>

        <td class="w-1-px">
          <% if user == current_user %>
            <%= image_tag('icon-star.png', class: "opacity-50") %>
          <% end %>
        </td>

        <td>
          <%= link_to user.name, user_path(user.id) %>
        </td>

        <td><%= user.email %></td>

        <td>
          <%  clazz = ''
              if user.admin?
                clazz = 'nav-item badge text-bg-danger'
              elsif user.user?
              elsif user.candidate?
                clazz = 'nav-item badge text-bg-success'
              else
                clazz = 'nav-item badge text-bg-warning'
              end
          %>
          <span class="<%= clazz %>"><%= user.display_role %></span>
        </td>

        <% if administration? %>
          <td>
            <%= link_to edit_user_path(user.id) do %>
              <%= render 'layouts/img_button', src: 'icon-edit.png', tooltip: 'Editieren' %>
            <% end %>
            <%= link_to user, data: { turbo_method: :delete, turbo_confirm: "Bist Du sicher?" } do %>
              <%= render 'layouts/img_button', src: 'icon-delete.png', tooltip: 'Löschen' %>
            <% end %>

            <% if user.candidate? %>
              <%= link_to accept_user_path(user.id), data: { turbo_method: :get, turbo_confirm: "Benutzer in die Gruppe aufnehmen?" } do %>
                <%= render 'layouts/img_button', src: 'icon-group-add.png', tooltip: 'Aufnehmen' %>
              <% end %>
            <% end %>
          </td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/users/new.html.erb
<div class="usk-header">Neuer Benutzer</div>

<%= form_for(@user) do |f| %>

  <div class="form-outline mb-4">
    <%= f.label :name, 'Name:', class: "form-label" %>
    <%= f.text_field :name, class: "form-control form-control-lg", placeholder: "Benutzername" %>
  </div>

  <!-- Email input -->
  <div class="form-outline mb-4">
    <%= f.label :email, 'E-Mail:', class: "form-label" %>
    <%= f.email_field :email, class: "form-control form-control-lg", placeholder: "E-Mail Adresse" %>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-3">
    <%= f.label :password, 'Passwort:', class: "form-label" %>
    <%= f.password_field :password, class: "form-control form-control-lg", placeholder: "Passwort" %>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-3">
    <%= f.label :password_confirmation, 'Passwort:', class: "form-label" %>
    <%= f.password_field :password_confirmation, class: "form-control form-control-lg", placeholder: "Passwort wiederholung" %>
  </div>

  <div class="usk-btn-group">
    <%= f.submit "Erstellen", class: "btn btn-primary" %>
    <%= link_to "Abbrechen", users_path, class: "btn btn-danger" %>
  </div>

<% end %>

rails/app/views/users/show.html.erb
<div class="usk-header">
  <% if @user == current_user %>
    Mein Profil:
  <% else %>
    Profil von <%= @user.name %>:
  <% end %>
</div>

<table class="table">
  <tbody>
    <tr>
      <th scope="row">Name</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th scope="row">E-Mail</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th scope="row">Role</th>
      <td><%= @user.display_role %></td>
    </tr>
    <tr>
      <th scope="row">Meine Gruppen</th>
      <td>
        <% @user.groups.each do |group| %>
          <%= link_to group.name, group_path(group.id) %><%= @user.groups.last == group ? '' : ', ' %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">Meine letzten Mitteilungen</th>
      <td>
        <ul class="list-group list-group-flush">
          <% @user.messages.reverse.take(3).each do |msg| %>
            <li class="list-group-item p-0">
              <%= link_to msg.subject, message_path(msg.id) %>
            </li>
          <% end %>
        </ul>
      </td>
    </tr>
  </tbody>
</table>