rails/config/routes.rb
Rails.application.routes.draw do
  get    '/service_worker', to: 'service_worker#service_worker'
  resources :push_subscriptions, only: :create
  resources :groups
  resources :users
  resources :messages
  get    '/messages/group/:id/new', to: 'messages#group_new', as: :new_group_message
  get    '/names_search/:query', to: 'names_search#search'
  get    '/groups/:id/user/:user_id', to: 'groups#add_remove_user', as: :user_in_group
  get    '/users/:id/accept', to: 'users#accept', as: :accept_user
  get    '/register' => 'register#new'
  post   '/register' => 'register#create'
  get    '/confirm/:id'  => 'register#confirm'
  get    '/password/:id'  => 'password#edit'
  post   '/password'  => 'password#update'
  get    '/login'    => 'sessions#new'
  post   '/login'    => 'sessions#create'
  delete '/logout'   => 'sessions#destroy'
  get    '/administration' => 'sessions#administration'
  get    '/impressum' => 'impressum#index'
  get    '/datenschutz' => 'impressum#datenschutz'
  get    '/logs'  => 'logs#index'
  root   'home#index'
end
  

rails/app/views/layouts/_add_button.html.erb
<button type="button" class="btn btn-light btn-sm" data-bs-toggle="tooltip" data-bs-title="<%= tooltip %>">
  <%= image_tag("icon-add.png") %>
</button>

rails/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-light">
  <div class="container-fluid flex-nowrap">

    <%= link_to "Urban Sketchers Aachen", root_path, id: "logo", class: "navbar-brand fw-bold usk-div-visible-up-lg" %>
    <%= link_to "Usk-AC", root_path, id: "logo", class: "navbar-brand fw-bold usk-div-visible-down-lg" %>

    <% if logged_in? %>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 me-auto">
        <div><%= link_to "Benutzer", users_path %></div>
        <div><%= link_to "Gruppen", groups_path %></div>
        <div><%= link_to "Mitteilungen", messages_path %></div>

        <% if administration? %>
          <div>
            <div class="badge text-bg-secondary">Administration an</div>
          </div>
        <% end %>
      </div>
    <% end %>

    <% unless administration? %>

      <div class="row row-cols-1 row-cols-md-2 me-1 ms-auto">
        <div class="text-end"><%= link_to "Datenschutz", datenschutz_path %></div>
        <div class="text-end"><%= link_to "Impressum", impressum_path %></div>
      </div>

    <% end %>

    <% if logged_in? %>

      <div class="dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_user.name %>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><%= link_to "Mein Profil", current_user, class: 'dropdown-item' %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Administrationsmodus " + (administration? ? 'aus' : 'an'), administration_path, class: 'dropdown-item' %></li>
            <% if administration? %>
              <li><%= link_to "Logs", logs_path, class: 'dropdown-item' %></li>
            <% end %>
          <% end %>
          <li class="dropdown-divider"></li>
          <li>
            <%= button_to "Abmelden", logout_path, method: :delete, class: 'dropdown-item' %>
          </li>
        </ul>
      </div>

    <% else %>

      <%= link_to "Anmelden", login_path, class: "active" %>

    <% end %>
 
  </div>
</nav>

rails/app/views/layouts/_img_button.html.erb
<button type="button" class="btn btn-light btn-sm" data-bs-toggle="tooltip" data-bs-title="<%= tooltip %>">
  <%= image_tag(src) %>
</button>

rails/app/views/layouts/_options.html.erb
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M480-160q-33 0-56.5-23.5T400-240q0-33 23.5-56.5T480-320q33 0 56.5 23.5T560-240q0 33-23.5 56.5T480-160Zm0-240q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400Zm0-240q-33 0-56.5-23.5T400-720q0-33 23.5-56.5T480-800q33 0 56.5 23.5T560-720q0 33-23.5 56.5T480-640Z"/></svg>

rails/app/views/layouts/_toast.html.erb
<% if flash.any? %>
  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <% flash.each do |message_type, message| %>

      <div class="toast text-bg-<%= message_type.to_s %>" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
          <strong class="me-auto">Usk-AC</strong>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
          <%= message %>
        </div>
      </div>

    <% end %>
  </div>
  <script>
    (function() {
      const toastElList = document.querySelectorAll('.toast')
      const toastList = [...toastElList].map(toastEl => bootstrap.Toast.getOrCreateInstance(toastEl, { delay: 3000 }))
      toastList.forEach( toast => toast.show() );
    }());
  </script>
<% end %>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UskAc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/header' %>

    <div class="container-fluid flex-column">

      <% if logged_in? %>

        <div class="text-center d-none" data-controller="subscribe" data-key="<%= ENV['VAPID_PUBLIC'] %>">
          Willst Du Push-Benachrichtigungen bekommen? -&gt;
          <button type="button" class="btn btn-primary btn-sm">Aktivieren</button>
        </div>
        
      <% end %>

      <div class="container-fluid flex-fill py-2">
        <%= yield %>
      </div>

    </div>

    <turbo-frame id="toast">
      <%= render 'layouts/toast' %>    
    </turbo-frame>

  </body>