rails/config/routes.rb
Rails.application.routes.draw do
  get    '/service_worker', to: 'service_worker#service_worker'
  resources :push_subscriptions, only: :create
  resources :groups
  resources :users
  resources :messages
  get    '/messages/group/:id/new', to: 'messages#group_new', as: :new_group_message
  get    '/names_search/:query', to: 'names_search#search'
  get    '/groups/:id/user/:user_id', to: 'groups#add_remove_user', as: :user_in_group
  get    '/users/:id/accept', to: 'users#accept', as: :accept_user
  get    '/register' => 'register#new'
  post   '/register' => 'register#create'
  get    '/confirm/:id'  => 'register#confirm'
  get    '/password/:id'  => 'password#edit'
  post   '/password'  => 'password#update'
  get    '/login'    => 'sessions#new'
  post   '/login'    => 'sessions#create'
  delete '/logout'   => 'sessions#destroy'
  get    '/administration' => 'sessions#administration'
  get    '/impressum' => 'impressum#index'
  get    '/datenschutz' => 'impressum#datenschutz'
  get    '/logs'  => 'logs#index'
  root   'home#index'
end
  

rails/app/models/group.rb
class Group < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 },
     uniqueness: { case_sensitive: false }

  validates :description,  presence: true, length: { maximum: 1024 }

  has_and_belongs_to_many :users
  has_many :messages

end

rails/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(ml_params)
    if @group.save
      flash[:success] = "Gruppe wurde zugefügt"
      log "Gruppe '#{@group.name}' wurde zugefügt"
      redirect_to groups_url
    else
      flash.now[:danger] = "Kann Gruppe nicht erstellen"
      render_toast
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    flash[:success] = "Gruppe '#{group.name}' wurde gelöscht"
    log "Gruppe '#{group.name}' wurde gelöscht"
    redirect_to groups_url
  end

  def edit
    @group = Group.find(params[:id])
    @users = User.all
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(ml_params)
      flash[:success] = "Gruppe wurde aktualisiert"
      log "Gruppe '#{@group.name}' wurde aktualisiert"
      redirect_to groups_url
    else
      render 'edit'
    end
  end

  def add_remove_user
    @group = Group.find(params[:id])
    user = User.find(params[:user_id])
    if @group && user
      if @group.users.include? user
        @group.users.delete user
        log "Mitglied '#{user.name}' wurde aus der Gruppe '#{@group.name}' entfernt"
      else
        @group.users.push user
        log "Mitglied '#{user.name}' wurde der Gruppe '#{@group.name}' hinzugefügt"
      end
      @group.save
      flash.now[:success] = "Gruppe wurde aktualisiert"
      render 'show'
    else
      redirect_to groups_url
    end
  end

  def ml_params
    params.require(:group).permit(:name, :description, :user_ids => [])
  end

end

rails/app/views/groups/edit.html.erb
<div class="usk-header">Gruppe editieren:</div>

<%= form_for(@group) do |f| %>

  <div class="mb-3">
    <%= f.label 'Name', class: "form-label" %>
    <%= f.text_field :name, class: "form-control", maxlength: 50 %>
  </div>

  <div class="mb-3">
    <%= f.label 'Beschreibung', class: "form-label" %>
    <%= f.text_area :description, rows: 4, class: "form-control", maxlength: 1024 %>
  </div>

  <div class="usk-btn-group">
    <%= f.submit "Speichern", class: "btn btn-primary" %>
    <%= link_to "Abbrechen", groups_path, class: "btn btn-danger" %>
  </div>

<% end %>

rails/app/views/groups/index.html.erb
<div class="d-flex justify-content-between">
  <div class="usk-header">
    Gruppen:
  </div>

  <% if administration? %>
    <%= link_to new_group_path do %>
      <%= render 'layouts/add_button', tooltip: 'Neue Liste' %>
    <% end %>
  <% end %>
</div>

<table class="table table-striped table-hover mt-3">
  <thead>
    <tr class="table-primary">
      <th></th>
      <th>Name</th>
      <th>Beschreibung</th>
      <th>Mitgliederzahl</th>
      <% if administration? %>
        <th>Aktion</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <% user_in = group.users.include? current_user %>
      <tr>

        <td class="w-1-px">
          <% if user_in %>
            <%= image_tag('icon-star.png', class: "opacity-50") %>
          <% end %>
        </td>

        <td>
          <%= link_to group.name, group_path(group.id) %>
        </td>

        <td><%= truncate(group.description, length: 64) %></td>

        <td><%= group.users.size.to_s + (group.users.size == 1 ? ' Person' : ' Personen') %></td>

        <% if administration? %>
          <td>
          
            <%= link_to edit_group_path(group.id) do %>
              <%= render 'layouts/img_button', src: 'icon-edit.png', tooltip: 'Editieren' %>
            <% end %>

            <%= link_to group, data: { turbo_method: :delete, turbo_confirm: "Bist Du sicher?" } do %>
              <%= render 'layouts/img_button', src: 'icon-delete.png', tooltip: 'Löschen' %>
            <% end %>

          </td>
        <% end %>

     </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/groups/new.html.erb
<div class="usk-header">
  Neue Gruppe:
</div>

<%= form_for(@group) do |f| %>

  <div class="mb-3">
    <%= f.label 'Name', class: "form-label" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Name der Gruppe", maxlength: 50 %>
  </div>

  <div class="mb-3">
    <%= f.label 'Beschreibung', class: "form-label" %>
    <%= f.text_area :description, rows: 4, class: "form-control", placeholder: "Beschreibung", maxlength: 1024 %>
  </div>

  <div class="usk-btn-group">
    <%= f.submit "Erstellen", class: "btn btn-primary" %>
    <%= link_to "Abbrechen", groups_path, class: "btn btn-danger" %>
  </div>

<% end %>

rails/app/views/groups/show.html.erb
<div class="d-flex justify-content-between">
  <div class="usk-header">
    Gruppe:
  </div>

  <div class="d-flex gap-2">
    <%= link_to new_group_message_path(@group.id) do %>
      <%= render 'layouts/img_button', src: 'icon-mail.png', tooltip: 'Mitteilung schreiben' %>
    <% end %>

    <%= link_to user_in_group_path(@group.id, current_user.id) do %>
      <%= user_in = @group.users.include? current_user
          render 'layouts/img_button', src: 'icon-group-' + (user_in ? 'remove' : 'add') + '.png', tooltip: user_in ? 'aus Liste entfernen' : 'in die Liste eintragen' %>
    <% end %>
  </div>
</div>

<table class="table mt-3">
  <tbody>
    <tr>
      <th scope="row">Name</th>
      <td><%= @group.name %></td>
    </tr>
    <tr>
      <th scope="row">Beschreibung</th>
      <td><%= simple_format @group.description %></td>
    </tr>
    <tr>
      <th scope="row">Mitglieder</th>
      <td>
        <div class="d-flex">
          <% @group.users.each do |user| %>
            <%= link_to user.name, user_path(user.id) %><%= @group.users.last == user ? '' : ', ' %>
          <% end %>
        </div>
      </td>
    </tr>
  </tbody>
</table>