rails/config/routes.rb
Rails.application.routes.draw do
  get    '/service_worker', to: 'service_worker#service_worker'
  resources :push_subscriptions, only: :create
  resources :groups
  resources :users
  resources :messages
  get    '/messages/group/:id/new', to: 'messages#group_new', as: :new_group_message
  get    '/names_search/:query', to: 'names_search#search'
  get    '/groups/:id/user/:user_id', to: 'groups#add_remove_user', as: :user_in_group
  get    '/users/:id/accept', to: 'users#accept', as: :accept_user
  get    '/register' => 'register#new'
  post   '/register' => 'register#create'
  get    '/confirm/:id'  => 'register#confirm'
  get    '/password/:id'  => 'password#edit'
  post   '/password'  => 'password#update'
  get    '/login'    => 'sessions#new'
  post   '/login'    => 'sessions#create'
  delete '/logout'   => 'sessions#destroy'
  get    '/administration' => 'sessions#administration'
  get    '/impressum' => 'impressum#index'
  get    '/datenschutz' => 'impressum#datenschutz'
  get    '/logs'  => 'logs#index'
  root   'home#index'
end
  

rails/app/models/message.rb
class Message < ApplicationRecord

  validates :content,  presence: true, length: { maximum: 2048 }

  belongs_to :user
  belongs_to :group, optional: true
  belongs_to :recipient, optional: true, class_name: 'User'

  def subject
    self.content.truncate 50
  end

end

rails/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @msg = Message.new
    @recipient = ''
    @msg.user = current_user
  end

  def group_new
    @msg = Message.new
    group = Group.find params[:id]
    @recipient = group ? group.name : ''
    @msg.user = current_user
    render 'new'
  end

  def new_user
  end

  def index
    current_user.notifications.delete_all
    
    @msgs = Message.all.order('created_at DESC')
    unless administration?
      me = current_user
      @msgs = Message.all.order('created_at DESC').select { |msg| msg.group || msg.recipient == me || msg.user == me }
    end
  end

  def show
    @msg = Message.find(params[:id])
  end
  
  def create
    recipient = (params[:recipient] || '').strip
    users = User.where_name_like recipient, 2
    groups = Group.where_name_like recipient, 2
    if (users.size + groups.size) == 1
      @msg = Message.new msg_params
      @msg.group_id = groups.first ? groups.first.id : nil
      @msg.recipient_id = users.first ? users.first.id : nil
      @msg.user_id = current_user.id

      if @msg.save
        flash[:success] = "Mitteilung wurde gespeichert"
        if @msg.group
          GroupMessageNotifier.with(msg_id: @msg.id).deliver current_user
          log "Neue Gruppen-Mitteilung an '#{@msg.group.name}'"
        else
          UserMessageNotifier.with(msg_id: @msg.id).deliver current_user
          log "Neue Benutzer-Mitteilung an '#{@msg.user.name}'"
        end
        redirect_to messages_url
      else
        flash.now[:danger] = "Speichern nicht möglich"
        render_toast
      end
    else
      flash.now[:danger] = "Empfänger nicht eindeutig"
      render_toast
    end
  end

  def edit
    @msg = Message.find(params[:id])
  end

  def update
    @msg = Message.find(params[:id])
    if @msg.update(msg_params)
      flash[:success] = "Mitteilung wurde aktualisiert"
      log "Mitteilung '#{@msg.group ? @msg.subject : @msg.id}' wurde aktualisiert"
      redirect_to messages_url
    else
      flash.now[:danger] = "Speichern nicht möglich"
      render_toast
    end
  end

  def destroy
    msg = Message.find(params[:id])
    if msg.destroy
      flash[:success] = "Mitteilung '#{msg.subject}' wurde gelöscht"
      log "Mitteilung '#{msg.group ? msg.subject : msg.id}' wurde gelöscht"
      redirect_to messages_url
    else
      flash.now[:danger] = "Löschen nicht möglich"
      render_toast
    end
  end

  private

  def msg_params
    params.require(:message).permit(:content, :user_id, :group_id)
  end

end

rails/app/views/messages/edit.html.erb
<div class="usk-header">Mitteilung editieren:</div>

<%= form_for(@msg) do |f| %>

  <div>
    <%= f.label 'Inhalt', class: "form-label" %>
    <%= f.text_area :content, rows: 6, class: "form-control" %>
  </div>
  
  <%= f.hidden_field :id %>

  <div class="usk-btn-group">
    <%= f.submit "Speichern", class: "btn btn-primary" %>
    <%= link_to "Abbrechen", messages_path, class: "btn btn-danger" %>
  </div>

<% end %>

rails/app/views/messages/index.html.erb
<div class="d-flex justify-content-between">
  <div class="usk-header">
    Mitteilungen:
  </div>

  <%= link_to new_message_path do %>
    <%= render 'layouts/add_button', tooltip: 'Neue Mitteilung' %>
  <% end %>
</div>

<table class="table table-striped table-hover mt-3">
  <thead>
    <tr class="table-primary">
      <th>Inhalt</th>
      <th>von</th>
      <th>an</th>
      <th>wann</th>
      <th>Aktion</th>
    </tr>
  </thead>
  <tbody>
    <% @msgs.each do |msg| %>
      <% mine = msg.user_id == current_user.id %>
      <tr>

        <td>
          <%= link_to msg.subject, message_path(msg.id) %>
        </td>

        <td class="<%= msg.user == current_user ? 'table-info' : '' %>">
          <%= link_to msg.user.name, user_path(msg.user.id) %>
        </td>

        <td class="<%= msg.recipient == current_user ? 'table-info' : '' %>">
          <% if msg.group %>
            <%= link_to msg.group.name, group_path(msg.group.id) %>
          <% elsif msg.recipient %>
            <%= link_to msg.recipient.name, user_path(msg.recipient.id) %>
          <% end %>
        </td>

        <td>
          <%= time_ago_in_words(msg.created_at) %>
        </td>

        <td>
          <% if administration? || mine %>
            <%= link_to edit_message_path(msg.id) do %>
              <%= render 'layouts/img_button', src: 'icon-edit.png', tooltip: 'Editieren' %>
            <% end %>

            <%= link_to msg, data: { turbo_method: :delete, turbo_confirm: "Bist Du sicher?" } do %>
              <%= render 'layouts/img_button', src: 'icon-delete.png', tooltip: 'Löschen' %>
            <% end %>
          <% end %>
        </td>
  
     </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/messages/new.html.erb
<div class="usk-header">
  Neue Mitteilung:
</div>

<%= form_for(@msg) do |f| %>

  <div class="mb-3">
    <%= f.label 'An', class: "form-label" %>
    <%= text_field_tag 'recipient', @recipient, class: "form-control", list: 'recipients', id: 'recipient' %>

    <datalist id='recipients'>
    </datalist>
  </div>

  <div class="mb-3">
    <%= f.label 'Inhalt', class: "form-label" %>
    <%= f.text_area :content, rows: 6, class: "form-control" %>
  </div>
  
  <div class="usk-btn-group">
    <%= f.submit "Speichern", class: "btn btn-primary" %>
    <%= link_to "Abbrechen", messages_path, class: "btn btn-danger" %>
  </div>

<% end %>

<script>
  document.querySelector('input#recipient').addEventListener( 'keyup', async (event) => {
    const result = await fetch(`/names_search/${encodeURIComponent(event.target.value)}`);
    const list = await result.json();
    const elem = document.querySelector('datalist#recipients');

    while (elem.firstChild)
      elem.removeChild(elem.lastChild);

    list.forEach( name => {
      const opt = document.createElement('option');
      opt.value = name;
      elem.appendChild(opt);
    });
  });
</script>

rails/app/views/messages/show.html.erb
<div class="usk-header">
  Mitteilung:
</div>

<table class="table mt-3">
  <tbody>
    <tr>
      <th scope="row">von</th>
      <td><%= link_to @msg.user.name, user_path(@msg.user.id) %></td>
    </tr>
    <tr>
      <th scope="row">an</th>
      <td>
          <% if @msg.group %>
            <%= link_to @msg.group.name, group_path(@msg.group.id) %>
          <% elsif @msg.recipient %>
            <%= link_to @msg.recipient.name, user_path(@msg.recipient.id) %>
          <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">wann</th>
      <td>
        <span><%= time_ago_in_words(@msg.created_at) %></span>
        <span class="fst-italic ms-4"><%= @msg.created_at.to_fs(:short) %></span>
      </td>
    </tr>
    <tr>
      <th scope="row">Inhalt</th>
      <td><%= simple_format @msg.content %></td>
    </tr>
  </tbody>
</table>